import type { Metadata } from "next";
import {Plus_Jakarta_Sans, Syne } from "next/font/google";
import "./globals.css";
import { Footer } from "./global/footer";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

const syne = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio Dev Gustavo Gantois",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="icon" type="image/svg+xml" href="/Logo.svg" />
        <link rel="alternate icon" href="/Logo.svg" />
      </head>
      <body
        className={`${plusJakartaSans.variable} ${syne.variable} antialiased`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
